### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by pphelper** [sycapple/MoMod#1]
百科查看升级版卡牌会崩溃比如天启犀牛围墙
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - MoMod (0.0.1)

Cause:
java.lang.RuntimeException: BaseMod failed to auto-generate makeCopy for card: momod:InstantShelter
	at basemod.abstracts.CustomCard.makeCopy(CustomCard.java:60)
	at com.megacrit.cardcrawl.cards.AbstractCard.renderInLibrary(AbstractCard.java:1237)
	at com.megacrit.cardcrawl.cards.CardGroup.renderInLibrary(CardGroup.java:898)
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.renderGroup(CardLibraryScreen.java:503)
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.render(CardLibraryScreen.java:424)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(MainMenuScreen.java:558)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

激活loadout印卡机后会崩溃
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - MoMod (0.0.1)
 - loadout (1.0.6)

Mods in stacktrace:
 - loadout (1.0.6)
Cause:
java.lang.RuntimeException: BaseMod failed to auto-generate makeCopy for card: momod:TacticalNukeSilo
	at basemod.abstracts.CustomCard.makeCopy(CustomCard.java:60)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:978)
	at basemod.abstracts.CustomCard.makeStatEquivalentCopy(CustomCard.java:573)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeSameInstanceOf(AbstractCard.java:972)
	at com.megacrit.cardcrawl.cards.CardGroup.<init>(CardGroup.java:66)
	at loadout.screens.GCardSelectScreen.open(GCardSelectScreen.java:717)
	at loadout.relics.CardPrinter.openSelectScreen(CardPrinter.java:42)
	at loadout.relics.AbstractCardScreenRelic.onRightClick(AbstractCardScreenRelic.java:85)
	at loadout.relics.AllInOneBag.update(AllInOneBag.java:380)
	at loadout.LoadoutMod.receivePostUpdate(LoadoutMod.java:907)
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2420)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:897)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

激活奇美拉卡牌加载时的提示（工坊搜chimera）
00:59:41.915 ERROR CardAugments.CardAugmentsMod> ERROR: Card momod:TacticalNukeSilo crashes when upgraded. Go yell at the mod author.
00:59:41.935 ERROR CardAugments.CardAugmentsMod> ERROR: Card momod:InstantShelter crashes when upgraded. Go yell at the mod author.
00:59:41.938 ERROR CardAugments.CardAugmentsMod> ERROR: Card momod:IronCurtainDevice crashes when upgraded. Go yell at the mod author.

会和另一个苏联mod产生冲突，在读档时排序在上面的会覆盖下面的。
举例
心灵终结苏联在上面，另一个苏联在下面，选另一个苏联开始游戏保存退出后，再继续游戏会发现人物变成基地车，后续卡牌奖励变成了心灵终结的卡池。
可能是内部的一些代码都用了Soviet作为识别标志，建议将本模组的代码改为SovietMO，后续的其他阵营的内部名字也建议加上MO。

围墙和碉堡功能类似建议给碉堡加一个每回合自动打出一个动员兵的效果，兵营能享受科技升级碉堡不能。

**Comment by sycapple** [comment]
收到
